urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
#from django.contrib.staticfiles.urls import staticfiles_urlpatterns
#from django.conf import settings
#from django.conf.urls.static import static
#from django.views.generic.simple import direct_to_template
from django.views.generic import TemplateView
from base_site.owl_video import views


admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'base_site.views.home', name='home'),
    # url(r'^base_site/', include('base_site.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'^comments/', include('django_comments.urls')), #copy templates from django.contrib.comments.templates
    #~ url(r'^comments/post/',  ),
    #~ url(r'^comments/', include('django.contrib.comments.urls')),
    
    url( r'^$', views.showIndex ),
    #~ url( r'^test/videos/$', direct_to_template, {'template' : 'flat_pages/videos.html'} ),
    #~ url( r'^test/video/$', direct_to_template, {'template' : 'flat_pages/video.html'} ),
    #~ url( r'^test/login/$', direct_to_template, {'template' : 'flat_pages/login.html'} ),
    #~ url( r'^test/create/$', direct_to_template, {'template' : 'flat_pages/register.html'} ),
    #~ url( r'^test/remind/$', direct_to_template, {'template' : 'flat_pages/pass_remind.html'} ),
    url( r'^test/videos/$', TemplateView.as_view( template_name = "flat_pages/videos.html" ) ),
    url( r'^test/video/$', TemplateView.as_view( template_name = "flat_pages/video.html" ) ),
    url( r'^test/video_panel/$', TemplateView.as_view( template_name = "flat_pages/video1.html" ) ),
    url( r'^test/login/$', TemplateView.as_view( template_name = "flat_pages/login.html" ) ),
    url( r'^test/create/$', TemplateView.as_view( template_name = "flat_pages/register.html" ) ),
    url( r'^test/remind/$', TemplateView.as_view( template_name = "flat_pages/pass_remind.html" ) ),
    
    url( r'^video/list/$', views.viewVideoList ),
    url( r'^video/(\d+)/$', views.viewVideoEntry ),
    url( r'^event/(\d+)/$', views.viewEventEntry ),
    url( r'^event/list/$', views.viewEventList ),
    #~ url( r'^view/user/$', views.viewVideoEntry ),
    #~ url( r'^view/event/$', views.viewVideoEntry ),
    #~ url( r'^event/list/$', views.viewVideoEntry ),
    
    url( r'^account/view/(\d+)/$', views.viewAccount ),
    url( r'^account/login/$', views.userLogin ),
    url( r'^account/logout/$', views.userLogout ),
    url( r'^account/create/$', views.userRegister ),
    url( r'^account/google_auth/$', views.userGrantAccessGoogle ),
    url( r'^account/google_callback/$', views.callBackHandlerFromGoogle ),
    #~ url( r'^test/account/$', direct_to_template, {'template' : 'flat_pages/account.html'} ),
    url( r'^test/account/$', TemplateView.as_view( template_name = "flat_pages/account.html" ) ),
    url( r'^test/email/$', TemplateView.as_view( template_name = "email.html" ) ),
    
    #~ url( r'^test/logged/$', direct_to_template, {'template' : 'htmls/log_head.html'} ),
    url( r'^test/logged/$', TemplateView.as_view( template_name = "htmls/log_head.html" ) ),
    url( r'^test/view/$', TemplateView.as_view( template_name = "base_anonym_account.html" ) ),
    url( r'^test/view-user/$', TemplateView.as_view( template_name = "flat_pages/account.html" ) ),
    url( r'^test/events/$', TemplateView.as_view( template_name = "flat_pages/events.html" ) ),
    url( r'^test/event/$', TemplateView.as_view( template_name = "flat_pages/event.html" ) ),
    url( r'^test/index/$', TemplateView.as_view( template_name = "flat_pages/index.html" ) ),
    url( r'^test/error404/$', TemplateView.as_view( template_name = "flat_pages/error_404.html" ) ),
    url( r'^test/error500/$', TemplateView.as_view( template_name = "flat_pages/error_500.html" ) ),
    url( r'^test/storage/$', TemplateView.as_view( template_name = "flat_pages/storage.html" ) ),
    url( r'^test/entry/$', TemplateView.as_view( template_name = "flat_pages/entry.html" ) ),
    url( r'^test/project/$', TemplateView.as_view( template_name = "flat_pages/project.html" ) ),
    url( r'^test/main/$', TemplateView.as_view( template_name = "flat_pages/main.html" ) ),
    
    url( r'^ajax/checkname/$', views.ajaxUserNameResolver ),
    url( r'^ajax/checkevent/$', views.ajaxEventNameResolver ),
    url( r'^appgetuser/$', views.sendLocalAppCreds ),
    url( r'^appreserve/$', views.reserveVideoId ),
    url( r'^appadddata/$', views.additionalVideoData ),
    url( r'^app_add_user_object/$', views.addUserArchiveObject ),
    url( r'^app_get_user_acc_places/$', views.getStorageProjectUserPerm ),
    url( r'^app_get_user_acc_archive/$', views.getUserAccessArchive )

    
    
)
# + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

#urlpatterns += staticfiles_urlpatterns()

owl_video/forms.py
# -*- coding: utf-8 -*-
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.hashers import check_password
from django.core.exceptions import ObjectDoesNotExist
from base_site.owl_video.models import Event
import re

#dict_arr_errors =  [ { 'required' : 'Требуется ввести Логин',
        #'min_length':'Логин не может быть короче 2-х символов',
        #'max_length':'Логин не может быть длинее 16-ти символов'
    #},
    #{'max_length':'Имя не может быть длинее 30-ти символов'},
    #{'max_length':'Фамилия не может быть длинее 30-ти символов'},
    #{'max_length':'Email не может быть длинее 255-ти символов',
        #'invalid':'Email не действителен',
        #'required' : 'Требуется ввести Email'
    #},
    #{'max_length':'Пароль не может быть длинее 32-х символов',
        #'required' : 'Требуется ввести Пароль'
    #},
    #{'max_length':'Пароль не может быть длинее 32-х символов',
        #'required' : 'Требуется ввести еще раз Пароль'
    #}
#]
def get_errors_dict(min_val=2, max_val=255, email=False):
    dict_errors = { 'required' : u'Необходимо заполнить' }
    dict_errors['max_length'] = u'Поле не может быть длинее чем {0} символ.'.format( max_val )
    dict_errors['min_length'] = u'Поле не может быть короче чем {0} символ.'.format( min_val )
    if email: dict_errors['invalid'] = u'Email не действителен'
    return dict_errors


class RegisterForm( forms.Form ):
    userlogin = forms.CharField( min_length = 2, max_length = 16, error_messages = get_errors_dict(2,16), widget=forms.TextInput( attrs={ 'class':'form-control','maxlength':'16','placeholder':'Введите псевдоним' } ) )
    name = forms.CharField( required = False, max_length = 30, error_messages = get_errors_dict(max_val=30), widget=forms.TextInput( attrs={ 'class':'form-control','maxlength':'30','placeholder':'Введите Ваше имя' } ) )
    surname = forms.CharField( required = False, max_length = 30, error_messages = get_errors_dict(max_val=30), widget=forms.TextInput( attrs={ 'class':'form-control','maxlength':'30','placeholder':'Введите Вашу фамилию' } ) )
    email = forms.EmailField( max_length = 255, error_messages = get_errors_dict( email=True ), widget=forms.TextInput( attrs={ 'class':'form-control','maxlength':'255','placeholder':'E-mail' } ) )
    #TODO email field, in django 1.6,, has EmailInput widget
    f_password = forms.CharField( max_length = 32, error_messages = get_errors_dict(max_val=32), widget=forms.PasswordInput( attrs={ 'class':'form-control','maxlength':'32','placeholder':'Ваш пароль' } ) )
    s_password = forms.CharField( max_length = 32, error_messages = get_errors_dict(max_val=32), widget=forms.PasswordInput( attrs={ 'class':'form-control','maxlength':'32','placeholder':'Ваш пароль, еще раз' } ) )
    
    def clean_name( self ):
        usname = self.cleaned_data.get( "surname", "" )
        uname = self.cleaned_data.get( "name", "" )
        match = re.compile(ur'^[a-zA-Z\u0400-\u04ff]*$')
        
        if not ( match.search( uname ) ) :
            raise forms.ValidationError(u"Поле может содержать только Кириллицу, Латиницу")
            
            
        #~ elif  ( not uname ) and ( usname != '' ) :
            #~ raise forms.ValidationError(u"Вы забыли ввести Ваше имя")
            
            
        return uname
    
    def clean_surname( self ):
        usname = self.cleaned_data.get( "surname", "" )
        uname = self.cleaned_data.get( "name", "" )
        match = re.compile(ur'^[a-zA-Z\u0400-\u04ff]*$')
        
        if not ( match.search( usname ) ) :
            raise forms.ValidationError(u"Поле может содержать только Кириллицу, Латиницу")
            
        #~ elif ( not usname ) and ( uname != '' ) :
            #~ raise forms.ValidationError(u"Вы забыли ввести Вашу фамилию")
            
            
        return usname
        
    def clean_userlogin( self ):
        ulogin = self.cleaned_data.get( "userlogin", "" )
        match = re.compile(ur'^[a-zA-Z0-9\+\.\-@_]+$')
        if not ( match.search( ulogin ) ) :
            raise forms.ValidationError(u"Разрешено использовать Латиницу, цифры и знаки: @ + - _ .")
            return ulogin
            
        try:
            User.objects.get( username = ulogin )
        except ObjectDoesNotExist:
            return ulogin
            
        raise forms.ValidationError(u"Логин: \'{0}\' уже занят".format( ulogin ) )
        return ulogin
        
    
    def clean_s_password( self ):
        f_pass = self.cleaned_data.get( "f_password", "" )
        s_pass = self.cleaned_data.get( "s_password", "" )
        match = re.compile(r'^\w+$')
        if not ( match.search( s_pass ) ) :
            raise forms.ValidationError(u"Разрешены только ASCII символы")
            return s_pass
        
        if f_pass != s_pass :
            raise forms.ValidationError(u"Пароли не совпадают")
            
        return s_pass
        
    def clean_f_password( self ):
        f_pass = self.cleaned_data.get( "f_password", "" )
        match = re.compile(r'^\w+$')
        if not ( match.search( f_pass ) ) :
            raise forms.ValidationError(u"Разрешены только ASCII символы")
        return f_pass

class LoginForm( forms.Form ):
    login_username = forms.CharField( min_length = 2, max_length = 70, error_messages = get_errors_dict(2,70), widget=forms.TextInput( attrs={ 'class':'form-control','maxlength':'70','placeholder':'Псевдоним' } ) )
    login_pass = forms.CharField( max_length = 32, error_messages = get_errors_dict(max_val=32), widget=forms.PasswordInput( attrs={ 'class':'form-control','maxlength':'32','placeholder':'Пароль' } ) )
    
    def clean_username( self ):
        username = self.cleaned_data.get( "login_username", "" )
        match = re.compile(r'^[a-zA-Z0-9\+\.\-@_]+$')
        if not ( match.search( username ) ) :
            raise forms.ValidationError(u"Разрешено использовать Латиницу, цифры и знаки: @ + - _ .")
        return username
        
    def clean_login_pass( self ):
        password = self.cleaned_data.get( "login_pass", "" )
        match = re.compile(r'^\w+$')
        if not ( match.search( password ) ) :
            raise forms.ValidationError(u"Разрешены только ASCII символы")
        return password

class PassRemindForm( forms.Form ):
    username = forms.CharField( min_length = 2, max_length = 16, error_messages = get_errors_dict(2,16), widget=forms.TextInput( attrs={ 'class':'form-control','maxlength':'16','placeholder':'Введите псевдоним' } ) )     
    email = forms.EmailField( max_length = 255, error_messages = get_errors_dict( email=True ), widget=forms.TextInput( attrs={ 'class':'form-control','maxlength':'255','placeholder':'E-mail' } ) )
        
    def clean_username( self ):
        uname = self.cleaned_data.get( "username", "" )
        match = re.compile(ur'^[a-zA-Z0-9\+\.\-@_]+$')
        if not ( match.search( uname ) ):
            raise forms.ValidationError(u"Разрешено использовать Латиницу, цифры и знаки: @ + - _ .")
        return uname

class SearchForm( forms.Form ):
    q = forms.CharField( required = False, max_length = 255, error_messages = get_errors_dict(), widget=forms.TextInput( attrs={ 'class':'form-control','maxlength':'255','placeholder':'Поиск по названию' } ) )
    search = forms.CharField( required = False, max_length = 255, error_messages = get_errors_dict(), widget=forms.HiddenInput( attrs={ 'value' : 'title' } ) )
    
    def clean_q( self ):
        query = self.cleaned_data.get( "q", "" )
        match = re.compile(ur'^[a-zA-Z0-9\u0400-\u04ff\+\.\-@_]*$')
        if not ( match.search( query ) ):
            raise forms.ValidationError(u"Для поиска разрешено использовать Латиницу, Кириллицу, цифры и знаки: @ + - _ .")
        return query

class CreateEventForm( forms.Form ):
    event_name = forms.CharField( min_length = 2, max_length = 255, error_messages = get_errors_dict(), widget=forms.TextInput( attrs={ 'class':'form-control','maxlength':'255','placeholder':'Введите имя события' } ) )
    event_desc = forms.CharField( required = False, max_length = 3000, error_messages = get_errors_dict( max_val = 3000 ), widget=forms.HiddenInput() )
    
    def clean_event_name( self ):
        event = self.cleaned_data.get( "event_name", "" )
        match = re.compile(ur'^[a-zA-Z0-9\u0400-\u04ff\+\.\-_]{2,255}$')
        if not ( match.search( event ) ):
            raise forms.ValidationError(u"<strong>Имя события</strong> может содержать только цифры и/или символы&#58; Кириллицы&#44; Латиницы&#44; + - _ .")
        try:
            Event.objects.get( name = event )
        except ObjectDoesNotExist:
            return event
        raise forms.ValidationError(u"Событие&#58; <strong>{event_name}</strong> уже существует".format( event_name = event ) )
        return event

class EditVideoDescForm( forms.Form ):
    video_desc = forms.CharField( required = False, max_length = 3000, error_messages = get_errors_dict( max_val = 3000 ), widget=forms.HiddenInput() )

class ChangeAccountDataForm( forms.Form ):
    pass

class ChangeAccountPassForm( forms.Form ):
    current_user_id = forms.CharField( widget=forms.HiddenInput() )
    current_pass = forms.CharField( max_length = 32, error_messages = get_errors_dict(max_val=32), widget=forms.PasswordInput( attrs={ 'class':'form-control','maxlength':'32','placeholder':'Введите текущий пароль' } ) )
    f_new_password = forms.CharField( max_length = 32, error_messages = get_errors_dict(max_val=32), widget=forms.PasswordInput( attrs={ 'class':'form-control','maxlength':'32','placeholder':'Введите новый пароль' } ) )
    s_new_password = forms.CharField( max_length = 32, error_messages = get_errors_dict(max_val=32), widget=forms.PasswordInput( attrs={ 'class':'form-control','maxlength':'32','placeholder':'Введите новый пароль, еще раз' } ) )
    
    def clean_s_new_password( self ):
        f_pass = self.cleaned_data.get( "f_new_password", "" )

templates/base.html
<!DOCTYPE html>
<html>
    <head>
        <title>{{ page_title }}</title>
    <!-- Bootstrap -->
        <meta charset="utf-8">
        <link href="/static/css/lumen_bootstrap.min.css" rel="stylesheet">
        <link href="/static/css/font-awesome-4.0.3/css/font-awesome.min.css" rel="stylesheet">
        <link href="/static/css/social-buttons-3.css" rel="stylesheet">
        <link href="/static/css/bootstrap-tour.min.css" rel="stylesheet">
<!--
        <link href="/static/css/bootstrap-theme.min.css" rel="stylesheet">
-->
        <link href="/static/css/owl.css" rel="stylesheet">
        {% block style %}{% endblock %}
    <!-- <link href="/static/css/non-responsive.css" rel="stylesheet"> -->

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
        <script src="/static/js/jquery-1.10.2.min.js"></script>
        <script src="/static/js/bootstrap.min.js"></script>
        <script src="/static/js/bootstrap-tour.min.js"></script>
        <script>
            $(document).ready( function() {
                //глобальный поиск из base.html
                var hidden_type = $("#id_search");
                var q_input = $("#id_q")
                $("#search_user").click( function() { hidden_type.val( 'user' ); q_input.attr( 'placeholder', "Поиск по пользователю" ); q_input.val(""); } );
                $("#search_event").click( function() { hidden_type.val( 'event' ); q_input.attr( 'placeholder', "Поиск по событию" ); q_input.val(""); } );
                $("#search_title").click( function() { hidden_type.val( 'title' ); q_input.attr( 'placeholder', "Поиск по названию" ); q_input.val(""); } );
            });
        </script>
        {% block scripts %}{% endblock %}
    </head>
    <body>
        <nav class="navbar navbar-default no-margin" role="navigation">
            <div class="col-sm-12">
                <div class="navbar-header">
                    <a class="navbar-brand" href="{% url 'base_site.owl_video.views.showIndex' %}">СОВА</a>
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav navbar-left">
                        <li><a href="{% url 'base_site.owl_video.views.viewVideoList' %}">Видеозаписи</a></li>
                        <li class="divdider"></li>
                        <li><a href="{% url 'base_site.owl_video.views.viewEventList' %}">События</a></li>
                        <li><a href="#" id="start_tour">Demo</a></li>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">

                        {% if user.is_authenticated %}
                        <li class="dropdown">
                            <a class="dropdown-toggle" data-toggle="dropdown">{{ user.username }}&#32;<b class="caret"></b></a>
                            <ul class="dropdown-menu">
                                <li class="dropdown-header">Видеоархив</li>
                                <li class="disabled"><a href="#">Добавить событие</a></li>
                                <li><a href="{% url 'base_site.owl_video.views.viewVideoList' %}?search=user&q={{ user.username }}">Мои видеозаписи</a></li>
                                <li class="divider"></li>
                                <li class="dropdown-header">Аккаунт</li>
                                <li><a href="{% url 'base_site.owl_video.views.viewAccount' user.id %}">Настройки</a></li>
                                <li><a href="{% url 'base_site.owl_video.views.userLogout' %}">Выйти <i class="fa fa-sign-out" style="color: rgb(153, 153, 153)"></i></a></li>
                            </ul>
                        </li>
                        {% else %}
                        <li><a href="{% url 'base_site.owl_video.views.userLogin' %}">Вход</a></li>
                        <li><a href="{% url 'base_site.owl_video.views.userRegister' %}">Регистрация</a></li>
                        {% endif %}
                    </ul>
                    <form method="get" action="{% url 'base_site.owl_video.views.viewVideoList' %}" class="col-sm-4 menu_search">
                        <div class="input-group">
                            <div class="input-group-btn">
                                <button type="button" class="btn btn-sm btn-default dropdown-toggle" data-toggle="dropdown"><i class="fa fa-adjust"></i> <i class="fa fa-caret-down"></i></button>
                                <ul class="dropdown-menu">
                                    <li class="dropdown-header">Искать по</li>
                                    <li><a id="search_title" href="#">названию</a></li>
                                    <li><a id="search_event" href="#">событию</a></li>
                                    <li><a id="search_user" href="#">пользователю</a></li>
                                </ul>
                            </div><!-- /btn-group -->
                            <input id="id_search" name="search" type="hidden" value="title" />
                            <input class="form-control form-sm" id="id_q" maxlength="255" name="q" placeholder="Поиск по названию" type="text" />
                        <span class="input-group-btn">
                            <button class="btn btn-success btn-sm" type="submit">Найти <i class="fa fa-search"></i></button>
                        </span>
                        </div><!-- /input-group -->
                    </form>

                </div>
            </div>
        </nav>

        <div class="container top_pad bottom_pad main_content" style="background-color: #fff;">

            {% block content %}{% endblock %}

        </div>
        <footer class="container">
            <div class="text-center">
                <span class="text-muted">Copyright@2014</span>
            </div>
        </footer>
    </body>
</html>

templates/base_anonym_account.html
{% extends "base.html" %}

{% block content %}
<div class="row">
    <div class="col-sm-3">
                <span class="fa-stack" style="font-size: 8.5em;">
                    <i class="fa fa-square-o fa-stack-2x"></i>
                    <i class="fa fa-question fa-stack-1x"></i>
                </span>
        {% comment %}
        <img src="/static/img/AT.gif" class="img-rounded" style="width: 100%; height: auto;">
        {% endcomment %}
    </div>
    <div class="col-sm-9">
        <div class="panel panel-default" >
            <div class="panel-heading">
                <h4 class="panel-title">Информация</h4>
            </div>
            <div class="panel-body">

                <form action="" method="post" role="form">
                    <div class="form-horizontal">
                        <div class="row" style="margin-bottom: 5px;">
                            <label class="col-sm-3 control-label">Логин:</label>
                            <div class="col-sm-9">
                                <div class="pull-left" style="padding-top: 7px;">
                                    <span>{{ shown_user.username }}</span>
                                </div>
                            </div>
                        </div>
                        <div class="row" style="margin-bottom: 5px;">
                            <label class="col-sm-3 control-label">Имя:</label>
                            <div class="col-sm-9">
                                <div class="pull-left" style="padding-top: 7px;">
                                    <span>
                                    {% if not shown_user.first_name %}
                                        <span class="text-muted">Отсутствует</span>
                                    {% else %}
                                        {{ shown_user.first_name }}
                                    {% endif %}
                                    </span>
                                </div>
                            </div>
                        </div>
                        <div class="row" style="margin-bottom: 5px;">
                            <label class="col-sm-3 control-label">Фамилия:</label>
                            <div class="col-sm-9">
                                <div class="pull-left" style="padding-top: 7px;">
                                    <span>
                                        {% if not shown_user.last_name %}
                                            <span class="text-muted">Отсутствует</span>
                                        {% else %}
                                            {{ shown_user.last_name }}
                                        {% endif %}
                                    </span>
                                </div>
                            </div>
                        </div>
                        <div class="row" style="margin-bottom: 5px;">
                            <label class="col-sm-3 control-label">E-mail:</label>
                            <div class="col-sm-9">
                                <div class="pull-left" style="padding-top: 7px;">
                                    <span>
                                        {% if user.is_authenticated and user.id == shown_user.id %}
                                            {{ shown_user.email }}
                                        {% else %}
                                            <span class="text-muted">Скрыт</span>
                                        {% endif %}
                                    </span>
                                </div>
                            </div>
                        </div>
                        <div class="row" style="margin-bottom: 5px;">
                            <label class="col-sm-3 control-label">Зарегистрирован:</label>
                            <div class="col-sm-9">
                                <div class="pull-left" style="padding-top: 7px;">
                                    <span>{{ shown_user.date_joined|date:"d.m.y" }}</span>
                                </div>
                            </div>
                        </div>
                        <div class="row" style="margin-bottom: 5px;">
                            <label class="col-sm-3 control-label">Последнее вход:</label>
                            <div class="col-sm-9">
                                <div class="pull-left" style="padding-top: 7px;">
                                    <span>{{ shown_user.last_login|date:"d.m.y в H:i" }}</span>
                                </div>
                            </div>
                        </div>

                    </div>
                </form>
            </div>
        </div>
        <div class="panel panel-default" style="margin-top: 10px;">
            <div class="panel-heading">
                <h4 class="panel-title">Статистика пользователя</h4>
            </div>
            <div class="panel-body">
                <div class="form-horizontal">
                    <div class="col-sm-6 no-paddings">
                        <div class="row" style="margin-bottom: 5px;">
                            <label class="col-sm-7 control-label">Добавлено видеозаписей:</label>
                            <div class="col-sm-5">
                                <div class="pull-left" style="padding-top: 7px;">
                                    <span><a href="{% url 'base_site.owl_video.views.viewVideoList' %}?search=user&q={{ shown_user.username }}">{{ shown_user.video_set.count }}</a></span>
                                </div>
                            </div>
                        </div>
                        <div class="row" style="margin-bottom: 5px;">
                            <label class="col-sm-7 control-label">Создано событий:</label>
                            <div class="col-sm-5">
                                <div class="pull-left" style="padding-top: 7px;">
                                    <span>{{ shown_user.event_set.count }}</span>
                                </div>
                            </div>
                        </div>
                        <div class="row" style="margin-bottom: 5px;">
                            <label class="col-sm-7 control-label">Оставлено комментариев:</label>
                            <div class="col-sm-5">
                                <div class="pull-left" style="padding-top: 7px;">
                                    <span>{{ shown_user.comment_comments.count }}</span>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>

    </div>
</div>

{% endblock %}

templates/base_event.html
{% extends "base.html" %}

{% block style %}
<link href="/static/css/summernote.css" rel="stylesheet">
<style>
    .note-editor .note-editable {
        overflow: auto;
        resize: none;
    }
    .note-editor .note-statusbar {
        display: none;
    }
</style>
{% endblock %}

{% block scripts %}
<script src="/static/js/summernote.min.js"></script>
<script src="/static/js/summernote-ru-RU.js"></script>
{% endblock %}

{% block content %}
<div class="col-sm-12" style="display:none;">
    <div class="alert alert-warning">I will warn you!</div>
</div>
<div class="row">
    <div class="col-sm-6" style="padding-right: 0;">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h4 class="panel-title">
                    {{ entry_event.name }}
                </h4>
            </div>
            <div class="panel-body">
                <h4>Описание события:</h4>
                <p>{{ entry_event.description|safe }}</p>
                <h4>Дополнительная информация:</h4>
                <label class="col-sm-5 text-right no-margin">Связано видеозаписей: </label>
                <a href="{% url 'base_site.owl_video.views.viewVideoList' %}?search=event&q={{ entry_event.name }}" class="col-sm-7 text-left">{{ entry_event.entrys.count }}</a>
                <label class="col-sm-5 text-right top_indent ">Создано пользователем: </label>
                <a href="{% url 'base_site.owl_video.views.viewAccount' entry_event.creator.id %}" class="col-sm-6 text-left top_indent">{{ entry_event.creator.username }}</a>

            </div>
        </div>
    </div>
    <div class="col-sm-6">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h4 class="panel-title"><i class="fa fa-comments"></i> Комментарии <small>&#40;0&#41;</small></h4>
            </div>
            <div class="panel-body">
                <ul class="media-list">
                    <p class="text-muted text-center">
                        <i class="fa fa-bullhorn"></i> Раздел в разработке
                    </p>
                </ul>
            </div>
        </div>
    </div>
</div>

{% endblock %}